---
- name: Apply standard configuration to all linux hosts
  hosts: '{{target|default("all")}}'
  tasks:
    - name: Apply SOE configuration to linux hosts
      ansible.builtin.debug:
        msg: "This applies our SOE configuration to all linux hosts (demo)."

    - ansible.builtin.debug:
        msg: "linter error"
