- name: Apply standard configuration to all linux hosts
  hosts: '{{target|default("all")}}'
  tasks:
    - name: Apply SOE configuration to linux hosts
      debug:
        msg: "This applies our SOE configuration to all linux hosts"
