- name: Apply standard configuration to all linux hosts
  hosts: '{{target|default("all")}}'
  tasks:
    - name: Configure SOE on linux hosts
      debug:
        msg: "This apply our SOE to all linux hosts"
